apiVersion: v1
kind: Service
metadata:
  name: uvd-backend
  namespace: universal-video-downloader
  labels:
    app.kubernetes.io/name: universal-video-downloader
    app.kubernetes.io/component: backend
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: universal-video-downloader
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
